# Generated by Django 3.2.16 on 2024-05-24 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolworkers',
            name='administrators_id',
        ),
        migrations.AlterField(
            model_name='parents',
            name='card_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cards', verbose_name='Номер карты родителя родителя'),
        ),
    ]
