# Generated by Django 3.2.16 on 2024-05-24 21:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Список блюд на завтрак',
            },
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checks_created_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания чека (datatime)')),
                ('checks_price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость чека (вычислимое поля)')),
            ],
            options={
                'verbose_name': 'Checks',
            },
        ),
        migrations.CreateModel(
            name='DinDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Список блюд на ужин',
            },
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes_name', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('dishes_description', models.TextField(max_length=1023, verbose_name='Описание блюда')),
                ('dishes_calories', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(750)], verbose_name='Калорийность блюда')),
                ('dishes_price', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Цена блюда')),
                ('valid_from_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала нахождения блюда в меню (datatime)')),
                ('valid_to_dttm', models.DateTimeField(verbose_name='Дата конца нахождения блюда в меню (datatime)')),
            ],
            options={
                'verbose_name': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='DishTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes_types_name', models.CharField(default='Напиток', max_length=255, verbose_name='Название типа блюда')),
            ],
            options={
                'verbose_name': 'Типа блюда',
            },
        ),
        migrations.CreateModel(
            name='LunDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lun_addition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lun_addition', to='food.dishes', verbose_name='Дополнительное, обеда')),
                ('lun_drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lun_drink', to='food.dishes', verbose_name='Напиток, завтрака')),
                ('lun_first', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lun_first', to='food.dishes', verbose_name='Первое, обеда')),
                ('lun_second_garnish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lun_second_garnish', to='food.dishes', verbose_name='Гарнир второе, обеда')),
                ('lun_second_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lun_second_main', to='food.dishes', verbose_name='Основное второе, обеда')),
            ],
            options={
                'verbose_name': 'Список блюд на обед',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_created_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа (datatime)')),
                ('orders_day_dt', models.DateField(verbose_name='Дата, на которую создан заказ')),
                ('orders_if_paid', models.BooleanField(default=False, verbose_name='Флаг, оплачен или нет')),
                ('orders_price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость заказа (вычислимое поля)')),
                ('children_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.children', verbose_name='id ребенка, на которого заказано блюдо')),
                ('orders_breakfast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.brdishes', verbose_name='id комплекта, в котором блюда для завтрака')),
                ('orders_dinner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dindishes', verbose_name='id комплекта, в котором блюда для ужина')),
                ('orders_lunch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.lundishes', verbose_name='id комплекта, в котором блюда для обеда')),
            ],
            options={
                'verbose_name': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_mark', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка отзыва')),
                ('reviews_text', models.TextField(max_length=1023, verbose_name='Текст отзыва')),
                ('reviews_created_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отзыва')),
                ('dishes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dishes', verbose_name='id блюда')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.parents', verbose_name='Оценка отзыва')),
            ],
            options={
                'verbose_name': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='OrdersInChecks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.checks')),
                ('orders_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.orders')),
            ],
        ),
        migrations.AddField(
            model_name='dishes',
            name='dishes_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dishtypes', verbose_name='Тип блюда'),
        ),
        migrations.AddField(
            model_name='dindishes',
            name='din_addition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='din_addition', to='food.dishes', verbose_name='Дополнительное, ужин'),
        ),
        migrations.AddField(
            model_name='dindishes',
            name='din_drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='din_drink', to='food.dishes', verbose_name='Напиток, ужин'),
        ),
        migrations.AddField(
            model_name='dindishes',
            name='din_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='din_main', to='food.dishes', verbose_name='Основное, ужин'),
        ),
        migrations.AddField(
            model_name='checks',
            name='orders_list',
            field=models.ManyToManyField(through='food.OrdersInChecks', to='food.Orders', verbose_name='Список заказов'),
        ),
        migrations.AddField(
            model_name='brdishes',
            name='br_addition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='br_addition', to='food.dishes', verbose_name='Дополнительное, завтрака'),
        ),
        migrations.AddField(
            model_name='brdishes',
            name='br_drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='br_drink', to='food.dishes', verbose_name='Напиток, завтрака'),
        ),
        migrations.AddField(
            model_name='brdishes',
            name='br_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='br_main', to='food.dishes', verbose_name='Основное, завтрака'),
        ),
    ]
