# Generated by Django 3.2.16 on 2024-06-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20240528_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='dindishes',
            name='din_garnish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='din_garnish', to='food.dishes', verbose_name='Гарнир ужина'),
        ),
    ]
