# Generated by Django 3.2.16 on 2024-06-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_dindishes_din_garnish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brdishes',
            name='br_addition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='br_addition', to='food.dishes', verbose_name='Дополнительное'),
        ),
        migrations.AlterField(
            model_name='brdishes',
            name='br_drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='br_drink', to='food.dishes', verbose_name='Напиток завтрака'),
        ),
        migrations.AlterField(
            model_name='brdishes',
            name='br_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='br_main', to='food.dishes', verbose_name='Основное завтрака'),
        ),
    ]
