# Generated by Django 3.2.16 on 2024-06-20 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240529_1624'),
        ('food', '0005_auto_20240620_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brdishes',
            name='br_child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.children', verbose_name='Ребенок'),
        ),
        migrations.AlterField(
            model_name='dindishes',
            name='din_child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.children', verbose_name='Ребенок'),
        ),
        migrations.AlterField(
            model_name='lundishes',
            name='lun_child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.children', verbose_name='Ребенок'),
        ),
    ]
